version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Root Config Test
          command: echo "Tynesha root CircleCI config is working"

workflows:
  test-workflow:
    jobs:
      - test